### ISSUE TITLE
U-Boot problem from MMC2

### ISSUE THREAD

**Issue by ugurkurt26** [embetrix/meta-coral-ai#2]
I'm attempting to run edgetpu-demo-image  on the Coral Dev Board via sd card. However, U-Boot hangs at the following stage during boot.
Commit:  [a5579cf](https://github.com/embetrix/meta-coral-ai/commit/a5579cf03a98d9c4d5610e613b9815504885068f) 
```
U-Boot SPL 2024.04-imx_v2024.04_6.6.36-2.1.0+gde16f4f1722+p0 (Sep 02 2024 - 10:44:35 +0000)
DDRINFO: start DRAM init
DDRINFO: DRAM rate 3200MTS
DDRINFO:ddrphy calibration done
DDRINFO: ddrmix config done
Normal Boot
Trying to boot from MMC2
```
have any suggest? Thx.

**Comment by embetrix** [comment]
@ugurkurt26 meta-freescale updated the u-boot and does not seems to work anymore, here the last commit working:

https://github.com/Freescale/meta-freescale/commits/41b923e59e048b9b2942ff737a4ddac386954c62

**Comment by ugurkurt26** [comment]
The suggestion worked, thank you!

**Comment by embetrix** [comment]
set fixed version of meta-freescale in the kas yaml file :  https://github.com/embetrix/meta-coral-ai/commit/7a9f79a9b55e3a786f2ae4b0ff2262d34d357732
